@startuml
'https://plantuml.com/class-diagram

abstract class Item {
    -itemDesc:String
    -due_date:Date
    -done:boolean
    +isDone():boolean
    +getDest():String
    +getDate():GregorianCalendar
    +editDesc():void
    +editDate():void
    +editDone():void
}



@enduml